const AWS_REGION = "us-east-1"
const DATABASE_NAME = "postgres"
const DATABASE_URL = '/DT/DATABASE/URL'
const DATABASE_USERNAME = '/DT/DATABASE/USERNAME'
const DATABASE_PASSWORD =  '/DT/DATABASE/PASSWORD'
const DATABASE_PORT = 5432

module.exports = {
   AWS_REGION, DATABASE_NAME, DATABASE_PASSWORD, DATABASE_PORT, DATABASE_URL, DATABASE_USERNAME
}